### ISSUE TITLE
Single main thread with non-blocking polling?

### ISSUE THREAD

**Issue by wmertens** [xogeny/aplus#7]
Sorry, this is not quite an issue. I'm wondering if it would be possible in Python to have a main loop like JavaScript, namely every blocking call goes onto a stack and the lowest call that becomes unblocked is handled next.

If so, it would be great to have aplus support that. The background() method is nice, but I doubt it's a good thing to have a couple thousand threads open to handle a bunch of blocking calls. NodeJS has proven that you rarely need more than a single thread for many applications...

**Comment by xogeny** [comment]
I didn't see this question when it was first posted and since it really isn't an issue I'm going to close it.

**Comment by wmertens** [comment]
Yes, not relevant any more 😅
